apiVersion: apps/v1
kind: Deployment


metadata:
  name: project-os2


spec:
  selector:
    matchLabels:
      app: reem
      
  replicas: 3
  template:
    metadata:
      name: my-first-pod
      labels:
        app: reem
    spec:
      containers:
        - image:  reemar87/nginx-testt
          name: nginx-container
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"     
            requests: 
              memory: "100Mi" 
